import { createHash, randomBytes, randomUUID, timingSafeEqual } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import argon2 from 'argon2';
import cookie from '@fastify/cookie';
import helmet from '@fastify/helmet';
import rateLimit from '@fastify/rate-limit';
import fastifyStatic from '@fastify/static';
import Fastify, { type FastifyRequest } from 'fastify';
import { z, ZodError } from 'zod';
import { audit, openDatabase, transaction, type Sqlite } from './database.js';
import { cityInput, csvHeaders, datePrecision, normalizeName, parseCanonicalCsv, tripInput, visitInput, writeCsv } from './domain.js';

type Auth = { id: string; username: string; displayName: string | null; role: 'admin' | 'user'; csrf: string; tokenHash: string };
type Row = Record<string, any>;
const hashToken = (token: string) => createHash('sha256').update(token).digest('hex');
const nowIso = () => new Date().toISOString();
const authByRequest = new WeakMap<FastifyRequest, Auth>();

const setupSchema = z.object({ username: z.string().trim().min(3).max(64).regex(/^[A-Za-z0-9._-]+$/), displayName: z.string().trim().max(120).optional(), password: z.string().min(12).max(1024), setupSecret: z.string().max(1024).optional() });
const loginSchema = z.object({ username: z.string().min(1).max(64), password: z.string().min(1).max(1024) });
const wishlistSchema = z.object({ countryCode: z.string().length(2).transform((v) => v.toUpperCase()), cityId: z.string().uuid().nullable().optional(), notes: z.string().max(5000).nullable().optional() });
const settingsSchema = z.object({ countryCountingMode: z.enum(['un195','iso3166','custom']).optional(), customCountryTotal: z.number().int().min(1).max(999).optional(), defaultMapLayer: z.enum(['visited','visit_count','city_count','recency']).optional(), showCityMarkers: z.boolean().optional(), cityMarkerZoomThreshold: z.number().min(1).max(8).optional(), csvSpreadsheetSafe: z.boolean().optional() });

function errorEnvelope(request: FastifyRequest, code: string, message: string, details?: unknown) { return { code, message, details, requestId: request.id }; }
function one(sqlite: Sqlite, sql: string, ...params: any[]) { return sqlite.prepare(sql).get(...params) as Row | undefined; }
function all(sqlite: Sqlite, sql: string, ...params: any[]) { return sqlite.prepare(sql).all(...params) as Row[]; }
function auth(request: FastifyRequest) { return authByRequest.get(request)!; }
function boolRows(rows: Row[]) { return rows.map((row) => Object.fromEntries(Object.entries(row).map(([key,value]) => [key, ['visited','wishlisted','enabled','showCityMarkers','csvSpreadsheetSafe'].includes(key) ? Boolean(value) : value]))); }

function countryQuery(sqlite: Sqlite, userId: string, where = '', ...params: any[]) {
  return boolRows(all(sqlite, `SELECT c.code_alpha2 code,c.code_alpha3 alpha3,c.numeric_code numericCode,c.name_en name,c.continent_code continentCode,c.region_name continent,
    c.kind,c.default_un195_counted un195Counted,c.default_iso_counted isoCounted,c.enabled,
    COUNT(v.id) visitCount,COUNT(DISTINCT v.city_id) cityCount,MIN(v.start_date) firstVisit,MAX(COALESCE(v.end_date,v.start_date)) lastVisit,
    CASE WHEN COUNT(v.id)>0 THEN 1 ELSE 0 END visited,CASE WHEN MAX(w.id) IS NOT NULL THEN 1 ELSE 0 END wishlisted
    FROM countries c LEFT JOIN visits v ON v.country_code=c.code_alpha2 AND v.user_id=? LEFT JOIN wishlist_items w ON w.country_code=c.code_alpha2 AND w.user_id=? AND w.city_id IS NULL
    WHERE c.enabled=1 ${where} GROUP BY c.code_alpha2 ORDER BY c.name_en`, userId, userId, ...params));
}
function cityQuery(sqlite: Sqlite, userId: string, where = '', ...params: any[]) {
  return boolRows(all(sqlite, `SELECT c.id,c.country_code countryCode,co.name_en countryName,c.name,c.admin1,c.admin2,c.latitude,c.longitude,c.created_at createdAt,c.updated_at updatedAt,
    COUNT(v.id) visitCount,MIN(v.start_date) firstVisit,MAX(COALESCE(v.end_date,v.start_date)) lastVisit,CASE WHEN COUNT(v.id)>0 THEN 1 ELSE 0 END visited,
    CASE WHEN MAX(w.id) IS NOT NULL THEN 1 ELSE 0 END wishlisted
    FROM cities c JOIN countries co ON co.code_alpha2=c.country_code LEFT JOIN visits v ON v.city_id=c.id AND v.user_id=? LEFT JOIN wishlist_items w ON w.city_id=c.id AND w.user_id=?
    WHERE c.user_id=? ${where} GROUP BY c.id ORDER BY c.name COLLATE NOCASE`, userId, userId, userId, ...params));
}
function visitQuery(sqlite: Sqlite, userId: string, where = '', ...params: any[]) {
  return all(sqlite, `SELECT v.id,v.country_code countryCode,co.name_en countryName,v.city_id cityId,c.name cityName,v.trip_id tripId,t.name tripName,
    v.start_date startDate,v.end_date endDate,v.date_precision datePrecision,v.notes,v.source,v.created_at createdAt,v.updated_at updatedAt
    FROM visits v JOIN countries co ON co.code_alpha2=v.country_code LEFT JOIN cities c ON c.id=v.city_id LEFT JOIN trips t ON t.id=v.trip_id
    WHERE v.user_id=? ${where} ORDER BY CASE WHEN v.start_date IS NULL THEN 1 ELSE 0 END,v.start_date DESC,v.created_at DESC`, userId, ...params);
}
function tripQuery(sqlite: Sqlite, userId: string, where = '', ...params: any[]) {
  return all(sqlite, `SELECT t.id,t.name,t.start_date startDate,t.end_date endDate,t.date_precision datePrecision,t.notes,t.created_at createdAt,t.updated_at updatedAt,
    COUNT(v.id) visitCount,COUNT(DISTINCT v.country_code) countryCount,COUNT(DISTINCT v.city_id) cityCount
    FROM trips t LEFT JOIN visits v ON v.trip_id=t.id AND v.user_id=? WHERE t.user_id=? ${where} GROUP BY t.id ORDER BY COALESCE(t.start_date,t.created_at) DESC`, userId, userId, ...params);
}

function assertReferences(sqlite: Sqlite, userId: string, input: z.infer<typeof visitInput>) {
  if (!one(sqlite, 'SELECT code_alpha2 FROM countries WHERE code_alpha2=? AND enabled=1', input.countryCode)) throw new Error('COUNTRY_NOT_FOUND');
  if (input.cityId) {
    const city = one(sqlite, 'SELECT country_code FROM cities WHERE id=? AND user_id=?', input.cityId, userId);
    if (!city) throw new Error('CITY_NOT_FOUND');
    if (city.country_code !== input.countryCode) throw new Error('CITY_COUNTRY_MISMATCH');
  }
  if (input.tripId && !one(sqlite, 'SELECT id FROM trips WHERE id=? AND user_id=?', input.tripId, userId)) throw new Error('TRIP_NOT_FOUND');
}

function createVisit(sqlite: Sqlite, userId: string, input: z.infer<typeof visitInput>, source = 'manual') {
  assertReferences(sqlite, userId, input);
  const duplicate = one(sqlite, `SELECT id FROM visits WHERE user_id=? AND country_code=? AND IFNULL(city_id,'')=IFNULL(?,'') AND IFNULL(trip_id,'')=IFNULL(?,'')
    AND IFNULL(start_date,'')=IFNULL(?,'') AND IFNULL(end_date,'')=IFNULL(?,'') AND IFNULL(notes,'')=IFNULL(?,'')`, userId,input.countryCode,input.cityId??null,input.tripId??null,input.startDate??null,input.endDate??null,input.notes??null);
  if (duplicate && !input.confirmDuplicate) throw new Error('DUPLICATE_VISIT');
  const id = randomUUID(); const timestamp = nowIso();
  sqlite.prepare(`INSERT INTO visits(id,user_id,country_code,city_id,trip_id,start_date,end_date,date_precision,notes,source,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`)
    .run(id,userId,input.countryCode,input.cityId??null,input.tripId??null,input.startDate??null,input.endDate??null,input.datePrecision,input.notes??null,source,timestamp,timestamp);
  return id;
}

export async function buildApp(options: { databasePath: string; cookieSecure: boolean; setupSecret?: string; bootstrapPassword?: string; staticRoot?: string }) {
  const app = Fastify({ logger: { redact: ['req.headers.cookie','req.headers.authorization','req.headers.x-csrf-token','body.password','body.notes','body.csv','body.backup'] }, trustProxy: false, bodyLimit: 2_200_000 });
  const sqlite = openDatabase(options.databasePath);
  const cookieName = options.cookieSecure ? '__Host-ryoiku_session' : 'ryoiku_session';
  await app.register(cookie);
  await app.register(helmet, { contentSecurityPolicy: { directives: { defaultSrc: ["'self'"], scriptSrc: ["'self'"], styleSrc: ["'self'"], imgSrc: ["'self'",'data:'], connectSrc: ["'self'"], upgradeInsecureRequests: options.cookieSecure ? [] : null } }, hsts: options.cookieSecure });
  await app.register(rateLimit, { max: 160, timeWindow: '1 minute' });

  const existing = one(sqlite, 'SELECT id FROM accounts LIMIT 1');
  if (!existing && options.bootstrapPassword) {
    if (options.bootstrapPassword.length < 12) throw new Error('Bootstrap password must have at least 12 characters.');
    const timestamp = nowIso(); const userId = randomUUID();
    const passwordHash = await argon2.hash(options.bootstrapPassword, { type: argon2.argon2id, memoryCost: 19456, timeCost: 2, parallelism: 1 });
    transaction(sqlite, () => {
      sqlite.prepare(`INSERT INTO accounts(id,username,display_name,password_hash,role,locale,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)`).run(userId,'admin','Administrator',passwordHash,'admin','en-US',timestamp,timestamp);
      sqlite.prepare(`INSERT INTO app_settings(user_id,updated_at) VALUES(?,?)`).run(userId,timestamp);
    });
  }

  app.setErrorHandler((error, request, reply) => {
    if (error instanceof ZodError) return reply.code(400).send(errorEnvelope(request,'VALIDATION_ERROR','Check the highlighted values.',error.flatten()));
    const issue = error instanceof Error ? error : new Error('Unknown request failure');
    if (issue.message === 'DUPLICATE_VISIT') return reply.code(409).send(errorEnvelope(request,'DUPLICATE_VISIT','This visit already exists. Confirm to save another copy.'));
    if (['COUNTRY_NOT_FOUND','CITY_NOT_FOUND','TRIP_NOT_FOUND'].includes(issue.message)) return reply.code(404).send(errorEnvelope(request,issue.message,'The referenced item was not found.'));
    if (issue.message === 'CITY_COUNTRY_MISMATCH') return reply.code(400).send(errorEnvelope(request,issue.message,'The city belongs to a different country.'));
    request.log.error({ err: error }, 'request failed');
    return reply.code(500).send(errorEnvelope(request,'INTERNAL_ERROR','Something went wrong. Try again.'));
  });

  app.addHook('preHandler', async (request, reply) => {
    const path = request.url.split('?')[0] ?? request.url;
    if (!path.startsWith('/api/v1/') || ['/api/v1/setup/status','/api/v1/setup','/api/v1/auth/login'].includes(path)) return;
    const token = request.cookies[cookieName];
    const timestamp = Date.now();
    const row = token ? one(sqlite, `SELECT s.token_hash tokenHash,s.csrf,s.idle_expires_at idleExpiresAt,s.absolute_expires_at absoluteExpiresAt,
      a.id,a.username,a.display_name displayName,a.role,a.disabled_at disabledAt FROM sessions s JOIN accounts a ON a.id=s.account_id WHERE s.token_hash=?`, hashToken(token)) : undefined;
    if (!row || row.disabledAt || Number(row.idleExpiresAt) < timestamp || Number(row.absoluteExpiresAt) < timestamp) {
      if (row) sqlite.prepare('DELETE FROM sessions WHERE token_hash=?').run(row.tokenHash);
      return reply.code(401).send(errorEnvelope(request,'AUTH_REQUIRED','Sign in to continue.'));
    }
    const current = row as unknown as Auth; authByRequest.set(request,current);
    sqlite.prepare('UPDATE sessions SET last_seen_at=?,idle_expires_at=? WHERE token_hash=?').run(timestamp,timestamp+30*60_000,current.tokenHash);
    if (!['GET','HEAD','OPTIONS'].includes(request.method) && request.headers['x-csrf-token'] !== current.csrf) return reply.code(403).send(errorEnvelope(request,'CSRF_INVALID','Refresh the page and try again.'));
  });

  app.get('/health/live', async () => ({ status: 'ok' }));
  app.get('/health/ready', async (_request, reply) => { try { sqlite.prepare('SELECT 1').get(); return { status: 'ready' }; } catch { return reply.code(503).send({ status: 'not-ready' }); } });
  app.get('/api/manifest', async () => ({ id:'ryoiku',name:'Ryoiku',version:process.env.APP_VERSION??'0.1.1',buildDate:process.env.BUILD_DATE??'development',gitSha:process.env.GIT_SHA??'development',countryDataset:'countries-list 3.4.1',mapDataset:'world-atlas 2.0.2',license:'Apache-2.0' }));
  app.get('/api/v1/setup/status', async () => ({ required: !one(sqlite,'SELECT id FROM accounts LIMIT 1'), setupSecretRequired: Boolean(options.setupSecret) }));
  app.post('/api/v1/setup', { config:{ rateLimit:{ max:5,timeWindow:'15 minutes' } } }, async (request,reply) => {
    const input = setupSchema.parse(request.body);
    if (one(sqlite,'SELECT id FROM accounts LIMIT 1')) return reply.code(409).send(errorEnvelope(request,'SETUP_CLOSED','Initial setup is already complete.'));
    if (options.setupSecret) {
      const supplied = Buffer.from(input.setupSecret ?? '');
      const expected = Buffer.from(options.setupSecret);
      if (supplied.length !== expected.length || !timingSafeEqual(supplied, expected)) {
        audit(sqlite,'first_run_setup','failure',request.id,undefined,{reason:'invalid_setup_secret'});
        return reply.code(401).send(errorEnvelope(request,'SETUP_UNAUTHORIZED','The setup credentials are invalid.'));
      }
    }
    const timestamp=nowIso(), id=randomUUID();
    const passwordHash=await argon2.hash(input.password,{type:argon2.argon2id,memoryCost:19456,timeCost:2,parallelism:1});
    transaction(sqlite,()=>{ sqlite.prepare(`INSERT INTO accounts(id,username,display_name,password_hash,role,locale,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)`).run(id,input.username,input.displayName??null,passwordHash,'admin','en-US',timestamp,timestamp); sqlite.prepare('INSERT INTO app_settings(user_id,updated_at) VALUES(?,?)').run(id,timestamp); });
    audit(sqlite,'first_run_setup','success',request.id,id); return reply.code(201).send({ created:true });
  });
  app.post('/api/v1/auth/login',{config:{rateLimit:{max:8,timeWindow:'5 minutes'}}},async(request,reply)=>{
    const input=loginSchema.safeParse(request.body); const account=input.success?one(sqlite,'SELECT * FROM accounts WHERE username=? COLLATE NOCASE',input.data.username):undefined;
    const valid=account&&input.success&&!account.disabled_at?await argon2.verify(String(account.password_hash),input.data.password):false;
    if(!valid||!account){audit(sqlite,'sign_in','failure',request.id,undefined,{usernameProvided:Boolean(input.success)});return reply.code(401).send(errorEnvelope(request,'AUTH_INVALID','Invalid credentials.'));}
    sqlite.prepare('DELETE FROM sessions WHERE account_id=? AND (idle_expires_at<? OR absolute_expires_at<?)').run(account.id,Date.now(),Date.now());
    const token=randomBytes(32).toString('base64url'),csrf=randomBytes(24).toString('base64url'),timestamp=Date.now();
    sqlite.prepare('INSERT INTO sessions(token_hash,account_id,csrf,created_at,last_seen_at,idle_expires_at,absolute_expires_at) VALUES(?,?,?,?,?,?,?)').run(hashToken(token),account.id,csrf,timestamp,timestamp,timestamp+30*60_000,timestamp+8*60*60_000);
    sqlite.prepare('UPDATE accounts SET last_login_at=?,updated_at=? WHERE id=?').run(nowIso(),nowIso(),account.id);
    reply.setCookie(cookieName,token,{path:'/',httpOnly:true,secure:options.cookieSecure,sameSite:'strict',maxAge:8*60*60}); audit(sqlite,'sign_in','success',request.id,String(account.id));
    return {csrf,user:{id:account.id,username:account.username,displayName:account.display_name,role:account.role}};
  });
  app.get('/api/v1/auth/me',async(request)=>{const user=auth(request);return {csrf:user.csrf,user:{id:user.id,username:user.username,displayName:user.displayName,role:user.role}};});
  app.post('/api/v1/auth/logout',async(request,reply)=>{const user=auth(request);sqlite.prepare('DELETE FROM sessions WHERE token_hash=?').run(user.tokenHash);reply.clearCookie(cookieName,{path:'/'});audit(sqlite,'sign_out','success',request.id,user.id);return reply.code(204).send();});

  app.get('/api/v1/countries',async(request)=>{const q=z.object({search:z.string().max(100).optional(),visited:z.enum(['all','visited','unvisited','wishlist']).optional()}).parse(request.query);let where='';const params:unknown[]=[];if(q.search){where+=' AND (c.name_en LIKE ? OR c.code_alpha2 LIKE ?)';params.push(`%${q.search}%`,`${q.search.toUpperCase()}%`);}const rows=countryQuery(sqlite,auth(request).id,where,...params);return q.visited==='visited'?rows.filter(r=>r.visited):q.visited==='unvisited'?rows.filter(r=>!r.visited):q.visited==='wishlist'?rows.filter(r=>r.wishlisted):rows;});
  app.get('/api/v1/countries/:code',async(request,reply)=>{const {code}=z.object({code:z.string().length(2)}).parse(request.params);const row=countryQuery(sqlite,auth(request).id,' AND c.code_alpha2=?',code.toUpperCase())[0];if(!row)return reply.code(404).send(errorEnvelope(request,'NOT_FOUND','Country not found.'));return {...row,visits:visitQuery(sqlite,auth(request).id,' AND v.country_code=?',code.toUpperCase()),cities:cityQuery(sqlite,auth(request).id,' AND c.country_code=?',code.toUpperCase())};});
  app.get('/api/v1/cities',async(request)=>{const q=z.object({search:z.string().max(100).optional(),country:z.string().length(2).optional()}).parse(request.query);let where='';const params:unknown[]=[];if(q.search){where+=' AND (c.name LIKE ? OR c.admin1 LIKE ?)';params.push(`%${q.search}%`,`%${q.search}%`);}if(q.country){where+=' AND c.country_code=?';params.push(q.country.toUpperCase());}return cityQuery(sqlite,auth(request).id,where,...params);});
  app.post('/api/v1/cities',async(request,reply)=>{const input=cityInput.parse(request.body),user=auth(request);if(!one(sqlite,'SELECT code_alpha2 FROM countries WHERE code_alpha2=?',input.countryCode))return reply.code(404).send(errorEnvelope(request,'COUNTRY_NOT_FOUND','Country not found.'));const duplicate=one(sqlite,'SELECT id FROM cities WHERE user_id=? AND country_code=? AND normalized_name=?',user.id,input.countryCode,normalizeName(input.name));const id=randomUUID(),timestamp=nowIso();sqlite.prepare(`INSERT INTO cities(id,user_id,country_code,name,normalized_name,admin1,admin2,latitude,longitude,is_custom,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,user.id,input.countryCode,input.name,normalizeName(input.name),input.admin1??null,input.admin2??null,input.latitude??null,input.longitude??null,1,timestamp,timestamp);return reply.code(201).send({id,duplicateOf:duplicate?.id??null});});
  app.get('/api/v1/cities/:id',async(request,reply)=>{const {id}=z.object({id:z.string().uuid()}).parse(request.params);const row=cityQuery(sqlite,auth(request).id,' AND c.id=?',id)[0];if(!row)return reply.code(404).send(errorEnvelope(request,'NOT_FOUND','City not found.'));return {...row,visits:visitQuery(sqlite,auth(request).id,' AND v.city_id=?',id)};});
  app.patch('/api/v1/cities/:id',async(request,reply)=>{const {id}=z.object({id:z.string().uuid()}).parse(request.params),input=cityInput.parse(request.body),user=auth(request);if(!one(sqlite,'SELECT id FROM cities WHERE id=? AND user_id=?',id,user.id))return reply.code(404).send(errorEnvelope(request,'NOT_FOUND','City not found.'));sqlite.prepare(`UPDATE cities SET country_code=?,name=?,normalized_name=?,admin1=?,admin2=?,latitude=?,longitude=?,updated_at=? WHERE id=? AND user_id=?`).run(input.countryCode,input.name,normalizeName(input.name),input.admin1??null,input.admin2??null,input.latitude??null,input.longitude??null,nowIso(),id,user.id);return {updated:true};});
  app.delete('/api/v1/cities/:id',async(request,reply)=>{const {id}=z.object({id:z.string().uuid()}).parse(request.params),q=z.object({mode:z.enum(['reject','delete_visits','country_only']).default('reject')}).parse(request.query),user=auth(request);const city=one(sqlite,'SELECT * FROM cities WHERE id=? AND user_id=?',id,user.id);if(!city)return reply.code(404).send(errorEnvelope(request,'NOT_FOUND','City not found.'));const count=Number((one(sqlite,'SELECT COUNT(*) count FROM visits WHERE city_id=? AND user_id=?',id,user.id)?.count??0));if(count&&q.mode==='reject')return reply.code(409).send(errorEnvelope(request,'CITY_HAS_VISITS','Choose whether to keep visits as country-only or delete them.'));transaction(sqlite,()=>{if(q.mode==='delete_visits')sqlite.prepare('DELETE FROM visits WHERE city_id=? AND user_id=?').run(id,user.id);else sqlite.prepare('UPDATE visits SET city_id=NULL,updated_at=? WHERE city_id=? AND user_id=?').run(nowIso(),id,user.id);sqlite.prepare('DELETE FROM cities WHERE id=? AND user_id=?').run(id,user.id);});return reply.code(204).send();});
  app.post('/api/v1/cities/:id/merge',async(request,reply)=>{const {id}=z.object({id:z.string().uuid()}).parse(request.params),{targetCityId}=z.object({targetCityId:z.string().uuid()}).parse(request.body),user=auth(request);if(id===targetCityId)return reply.code(400).send(errorEnvelope(request,'MERGE_SAME_CITY','Choose a different target city.'));const source=one(sqlite,'SELECT * FROM cities WHERE id=? AND user_id=?',id,user.id),target=one(sqlite,'SELECT * FROM cities WHERE id=? AND user_id=?',targetCityId,user.id);if(!source||!target)return reply.code(404).send(errorEnvelope(request,'NOT_FOUND','Both cities must belong to your account.'));if(source.country_code!==target.country_code)return reply.code(400).send(errorEnvelope(request,'MERGE_COUNTRY_MISMATCH','Cities can only be merged within the same country.'));transaction(sqlite,()=>{sqlite.prepare('UPDATE visits SET city_id=?,updated_at=? WHERE city_id=? AND user_id=?').run(targetCityId,nowIso(),id,user.id);const sourceWish=one(sqlite,'SELECT id FROM wishlist_items WHERE city_id=? AND user_id=?',id,user.id);if(sourceWish){if(one(sqlite,'SELECT id FROM wishlist_items WHERE city_id=? AND user_id=?',targetCityId,user.id))sqlite.prepare('DELETE FROM wishlist_items WHERE id=?').run(sourceWish.id);else sqlite.prepare('UPDATE wishlist_items SET city_id=? WHERE id=?').run(targetCityId,sourceWish.id);}sqlite.prepare('DELETE FROM cities WHERE id=? AND user_id=?').run(id,user.id);});audit(sqlite,'city_merge','success',request.id,user.id,{sourceCityId:id,targetCityId});return {merged:true,targetCityId};});

  app.get('/api/v1/visits',async(request)=>{const q=z.object({country:z.string().length(2).optional(),city:z.string().uuid().optional(),trip:z.string().uuid().optional()}).parse(request.query);let where='';const params:unknown[]=[];if(q.country){where+=' AND v.country_code=?';params.push(q.country.toUpperCase());}if(q.city){where+=' AND v.city_id=?';params.push(q.city);}if(q.trip){where+=' AND v.trip_id=?';params.push(q.trip);}return visitQuery(sqlite,auth(request).id,where,...params);});
  app.post('/api/v1/visits',async(request,reply)=>{const input=visitInput.parse(request.body),id=createVisit(sqlite,auth(request).id,input);return reply.code(201).send({id});});
  app.get('/api/v1/visits/:id',async(request,reply)=>{const {id}=z.object({id:z.string().uuid()}).parse(request.params);const row=visitQuery(sqlite,auth(request).id,' AND v.id=?',id)[0];return row??reply.code(404).send(errorEnvelope(request,'NOT_FOUND','Visit not found.'));});
  app.patch('/api/v1/visits/:id',async(request,reply)=>{const {id}=z.object({id:z.string().uuid()}).parse(request.params),input=visitInput.parse(request.body),user=auth(request);if(!one(sqlite,'SELECT id FROM visits WHERE id=? AND user_id=?',id,user.id))return reply.code(404).send(errorEnvelope(request,'NOT_FOUND','Visit not found.'));assertReferences(sqlite,user.id,input);sqlite.prepare(`UPDATE visits SET country_code=?,city_id=?,trip_id=?,start_date=?,end_date=?,date_precision=?,notes=?,updated_at=? WHERE id=? AND user_id=?`).run(input.countryCode,input.cityId??null,input.tripId??null,input.startDate??null,input.endDate??null,input.datePrecision,input.notes??null,nowIso(),id,user.id);return {updated:true};});
  app.delete('/api/v1/visits/:id',async(request,reply)=>{const {id}=z.object({id:z.string().uuid()}).parse(request.params);sqlite.prepare('DELETE FROM visits WHERE id=? AND user_id=?').run(id,auth(request).id);return reply.code(204).send();});

  app.get('/api/v1/trips',async(request)=>tripQuery(sqlite,auth(request).id));
  app.post('/api/v1/trips',async(request,reply)=>{const input=tripInput.parse(request.body),user=auth(request),id=randomUUID(),timestamp=nowIso();sqlite.prepare(`INSERT INTO trips(id,user_id,name,start_date,end_date,date_precision,notes,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)`).run(id,user.id,input.name,input.startDate??null,input.endDate??null,input.datePrecision,input.notes??null,timestamp,timestamp);return reply.code(201).send({id});});
  app.get('/api/v1/trips/:id',async(request,reply)=>{const {id}=z.object({id:z.string().uuid()}).parse(request.params);const row=tripQuery(sqlite,auth(request).id,' AND t.id=?',id)[0];return row?{...row,visits:visitQuery(sqlite,auth(request).id,' AND v.trip_id=?',id)}:reply.code(404).send(errorEnvelope(request,'NOT_FOUND','Trip not found.'));});
  app.patch('/api/v1/trips/:id',async(request,reply)=>{const {id}=z.object({id:z.string().uuid()}).parse(request.params),input=tripInput.parse(request.body),user=auth(request);const result=sqlite.prepare(`UPDATE trips SET name=?,start_date=?,end_date=?,date_precision=?,notes=?,updated_at=? WHERE id=? AND user_id=?`).run(input.name,input.startDate??null,input.endDate??null,input.datePrecision,input.notes??null,nowIso(),id,user.id);if(!result.changes)return reply.code(404).send(errorEnvelope(request,'NOT_FOUND','Trip not found.'));return {updated:true};});
  app.delete('/api/v1/trips/:id',async(request,reply)=>{const {id}=z.object({id:z.string().uuid()}).parse(request.params),user=auth(request);transaction(sqlite,()=>{sqlite.prepare('UPDATE visits SET trip_id=NULL,updated_at=? WHERE trip_id=? AND user_id=?').run(nowIso(),id,user.id);sqlite.prepare('DELETE FROM trips WHERE id=? AND user_id=?').run(id,user.id);});return reply.code(204).send();});

  app.get('/api/v1/wishlist',async(request)=>all(sqlite,`SELECT w.id,w.country_code countryCode,co.name_en countryName,w.city_id cityId,c.name cityName,w.notes,w.created_at createdAt FROM wishlist_items w JOIN countries co ON co.code_alpha2=w.country_code LEFT JOIN cities c ON c.id=w.city_id WHERE w.user_id=? ORDER BY co.name_en,c.name`,auth(request).id));
  app.post('/api/v1/wishlist',async(request,reply)=>{const input=wishlistSchema.parse(request.body),user=auth(request),id=randomUUID();if(!one(sqlite,'SELECT code_alpha2 FROM countries WHERE code_alpha2=?',input.countryCode))return reply.code(404).send(errorEnvelope(request,'COUNTRY_NOT_FOUND','Country not found.'));try{sqlite.prepare('INSERT INTO wishlist_items(id,user_id,country_code,city_id,notes,created_at) VALUES(?,?,?,?,?,?)').run(id,user.id,input.countryCode,input.cityId??null,input.notes??null,nowIso());}catch{return reply.code(409).send(errorEnvelope(request,'WISHLIST_DUPLICATE','That destination is already on your wishlist.'));}return reply.code(201).send({id});});
  app.delete('/api/v1/wishlist/:id',async(request,reply)=>{const {id}=z.object({id:z.string().uuid()}).parse(request.params);sqlite.prepare('DELETE FROM wishlist_items WHERE id=? AND user_id=?').run(id,auth(request).id);return reply.code(204).send();});

  app.get('/api/v1/stats/summary',async(request)=>{const user=auth(request);const totals=one(sqlite,`SELECT COUNT(*) visitCount,COUNT(DISTINCT country_code) countryCount,COUNT(DISTINCT city_id) cityCount,COUNT(DISTINCT trip_id) tripCount FROM visits WHERE user_id=?`,user.id)!;const settings=one(sqlite,'SELECT country_counting_mode mode,custom_country_total customTotal FROM app_settings WHERE user_id=?',user.id)!;const countryTotal=settings.mode==='custom'?Number(settings.customTotal):Number(one(sqlite,`SELECT COUNT(*) count FROM countries WHERE enabled=1 AND ${settings.mode==='iso3166'?'default_iso_counted':'default_un195_counted'}=1`)?.count);const recent=visitQuery(sqlite,user.id).slice(0,6);return {...totals,countryTotal,countryCountingMode:settings.mode,wishlistCount:one(sqlite,'SELECT COUNT(*) count FROM wishlist_items WHERE user_id=?',user.id)?.count??0,recent};});
  app.get('/api/v1/stats/continents',async(request)=>all(sqlite,`SELECT c.continent_code code,c.region_name name,COUNT(DISTINCT v.country_code) visitedCountries,COUNT(v.id) visits FROM countries c LEFT JOIN visits v ON v.country_code=c.code_alpha2 AND v.user_id=? WHERE c.enabled=1 GROUP BY c.continent_code ORDER BY c.region_name`,auth(request).id));
  app.get('/api/v1/stats/timeline',async(request)=>all(sqlite,`SELECT SUBSTR(start_date,1,4) year,COUNT(*) visits,COUNT(DISTINCT country_code) countries FROM visits WHERE user_id=? AND start_date IS NOT NULL GROUP BY SUBSTR(start_date,1,4) ORDER BY year`,auth(request).id));
  app.get('/api/v1/stats/rankings',async(request)=>({countries:all(sqlite,`SELECT c.code_alpha2 code,c.name_en name,COUNT(v.id) visits FROM visits v JOIN countries c ON c.code_alpha2=v.country_code WHERE v.user_id=? GROUP BY v.country_code ORDER BY visits DESC,c.name_en LIMIT 10`,auth(request).id),cities:all(sqlite,`SELECT c.id,c.name,co.name_en countryName,COUNT(v.id) visits FROM visits v JOIN cities c ON c.id=v.city_id JOIN countries co ON co.code_alpha2=c.country_code WHERE v.user_id=? GROUP BY v.city_id ORDER BY visits DESC,c.name LIMIT 10`,auth(request).id)}));
  app.get('/api/v1/map/summary',async(request)=>countryQuery(sqlite,auth(request).id));
  app.get('/api/v1/map/cities',async(request)=>cityQuery(sqlite,auth(request).id,' AND c.latitude IS NOT NULL AND c.longitude IS NOT NULL'));

  app.get('/api/v1/settings',async(request)=>{const row=one(sqlite,`SELECT country_counting_mode countryCountingMode,custom_country_total customCountryTotal,default_map_layer defaultMapLayer,show_city_markers showCityMarkers,city_marker_zoom_threshold cityMarkerZoomThreshold,csv_spreadsheet_safe csvSpreadsheetSafe FROM app_settings WHERE user_id=?`,auth(request).id)!;return {...row,showCityMarkers:Boolean(row.showCityMarkers),csvSpreadsheetSafe:Boolean(row.csvSpreadsheetSafe)};});
  app.patch('/api/v1/settings',async(request)=>{const input=settingsSchema.parse(request.body),user=auth(request);const current=one(sqlite,'SELECT * FROM app_settings WHERE user_id=?',user.id)!;sqlite.prepare(`UPDATE app_settings SET country_counting_mode=?,custom_country_total=?,default_map_layer=?,show_city_markers=?,city_marker_zoom_threshold=?,csv_spreadsheet_safe=?,updated_at=? WHERE user_id=?`).run(input.countryCountingMode??current.country_counting_mode,input.customCountryTotal??current.custom_country_total,input.defaultMapLayer??current.default_map_layer,input.showCityMarkers==null?current.show_city_markers:Number(input.showCityMarkers),input.cityMarkerZoomThreshold??current.city_marker_zoom_threshold,input.csvSpreadsheetSafe==null?current.csv_spreadsheet_safe:Number(input.csvSpreadsheetSafe),nowIso(),user.id);return {updated:true};});

  app.post('/api/v1/import/csv/preview',async(request,reply)=>{const body=z.object({csv:z.string().min(1)}).parse(request.body),user=auth(request);let rows;try{rows=parseCanonicalCsv(body.csv);}catch(error){return reply.code(400).send(errorEnvelope(request,'CSV_INVALID',error instanceof Error?error.message:'CSV could not be parsed.'));}const errors:{row:number;message:string}[]=[],warnings:{row:number;message:string}[]=[];rows.forEach((row,index)=>{if(!['visit','wishlist'].includes(row.record_type))errors.push({row:index+2,message:'record_type must be visit or wishlist.'});if(!one(sqlite,'SELECT code_alpha2 FROM countries WHERE code_alpha2=? AND enabled=1',row.country_code.toUpperCase()))errors.push({row:index+2,message:'Unknown country code.'});if(row.date_precision&&!datePrecision.safeParse(row.date_precision).success)errors.push({row:index+2,message:'Invalid date precision.'});if(row.visited_from&&!/^\d{4}-\d{2}-\d{2}$/.test(row.visited_from))errors.push({row:index+2,message:'Invalid start date.'});if(row.visited_to&&!/^\d{4}-\d{2}-\d{2}$/.test(row.visited_to))errors.push({row:index+2,message:'Invalid end date.'});if(row.visited_from&&row.visited_to&&row.visited_to<row.visited_from)errors.push({row:index+2,message:'End date precedes start date.'});if(row.latitude&&(!Number.isFinite(Number(row.latitude))||Math.abs(Number(row.latitude))>90))errors.push({row:index+2,message:'Invalid latitude.'});if(row.longitude&&(!Number.isFinite(Number(row.longitude))||Math.abs(Number(row.longitude))>180))errors.push({row:index+2,message:'Invalid longitude.'});if(row.city_name&&one(sqlite,'SELECT id FROM cities WHERE user_id=? AND country_code=? AND normalized_name=?',user.id,row.country_code.toUpperCase(),normalizeName(row.city_name)))warnings.push({row:index+2,message:'Existing city will be reused.'});});const id=randomUUID(),payload={rows,errors,warnings};sqlite.prepare('INSERT INTO import_previews(id,user_id,kind,payload,created_at,expires_at) VALUES(?,?,?,?,?,?)').run(id,user.id,'csv',JSON.stringify(payload),Date.now(),Date.now()+30*60_000);return {previewId:id,summary:{rows:rows.length,valid:rows.length-new Set(errors.map(e=>e.row)).size,errors:errors.length,warnings:warnings.length},errors,warnings,rows:rows.slice(0,100)};});
  app.post('/api/v1/import/csv/commit',async(request,reply)=>{const {previewId}=z.object({previewId:z.string().uuid()}).parse(request.body),user=auth(request);const preview=one(sqlite,'SELECT payload FROM import_previews WHERE id=? AND user_id=? AND kind=? AND expires_at>?',previewId,user.id,'csv',Date.now());if(!preview)return reply.code(404).send(errorEnvelope(request,'PREVIEW_EXPIRED','Create a new import preview.'));const payload=JSON.parse(String(preview.payload)) as {rows:Record<string,string>[];errors:unknown[]};if(payload.errors.length)return reply.code(409).send(errorEnvelope(request,'IMPORT_HAS_ERRORS','Fix all row errors before importing.'));let createdVisits=0,createdCities=0,createdTrips=0,createdWishlist=0;transaction(sqlite,()=>{for(const row of payload.rows){const code=row.country_code!.toUpperCase();let tripId:null|string=null,cityId:null|string=null;if(row.trip_name){const trip=one(sqlite,'SELECT id FROM trips WHERE user_id=? AND name=? COLLATE NOCASE',user.id,row.trip_name);tripId=String(trip?.id??randomUUID());if(!trip){const t=nowIso();sqlite.prepare(`INSERT INTO trips(id,user_id,name,date_precision,created_at,updated_at) VALUES(?,?,?,?,?,?)`).run(tripId,user.id,row.trip_name,'unknown',t,t);createdTrips++;}}if(row.city_name){const city=one(sqlite,'SELECT id FROM cities WHERE user_id=? AND country_code=? AND normalized_name=?',user.id,code,normalizeName(row.city_name));cityId=String(city?.id??randomUUID());if(!city){const t=nowIso();sqlite.prepare(`INSERT INTO cities(id,user_id,country_code,name,normalized_name,admin1,admin2,latitude,longitude,is_custom,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`).run(cityId,user.id,code,row.city_name,normalizeName(row.city_name),row.admin1||null,row.admin2||null,row.latitude?Number(row.latitude):null,row.longitude?Number(row.longitude):null,1,t,t);createdCities++;}}if(row.record_type==='wishlist'){try{sqlite.prepare('INSERT INTO wishlist_items(id,user_id,country_code,city_id,notes,created_at) VALUES(?,?,?,?,?,?)').run(randomUUID(),user.id,code,cityId,row.notes||null,nowIso());createdWishlist++;}catch{continue;}}else{try{createVisit(sqlite,user.id,{countryCode:code,cityId,tripId,startDate:row.visited_from||null,endDate:row.visited_to||null,datePrecision:(datePrecision.safeParse(row.date_precision).success?row.date_precision:'unknown') as z.infer<typeof datePrecision>,notes:row.notes||null},'csv_import');createdVisits++;}catch(error){if(error instanceof Error&&error.message==='DUPLICATE_VISIT')continue;throw error;}}}sqlite.prepare('DELETE FROM import_previews WHERE id=?').run(previewId);});return {createdVisits,createdCities,createdTrips,createdWishlist};});

  app.get('/api/v1/export/visits.csv',async(request,reply)=>{const user=auth(request),safe=Boolean(one(sqlite,'SELECT csv_spreadsheet_safe safe FROM app_settings WHERE user_id=?',user.id)?.safe);const rows=visitQuery(sqlite,user.id).map((v)=>({record_type:'visit',visit_id:v.id,country_code:v.countryCode,country_name:v.countryName,city_name:v.cityName,admin1:'',admin2:'',latitude:'',longitude:'',visited_from:v.startDate,visited_to:v.endDate,date_precision:v.datePrecision,trip_name:v.tripName,notes:v.notes}));reply.type('text/csv; charset=utf-8').header('Content-Disposition','attachment; filename="ryoiku-visits.csv"');return writeCsv(rows,csvHeaders,safe);});
  app.get('/api/v1/export/cities.csv',async(request,reply)=>{const columns=['country_code','country_name','city_name','admin1','latitude','longitude','visit_count','first_visit','last_visit'];const rows=cityQuery(sqlite,auth(request).id).map(c=>({country_code:c.countryCode,country_name:c.countryName,city_name:c.name,admin1:c.admin1,latitude:c.latitude,longitude:c.longitude,visit_count:c.visitCount,first_visit:c.firstVisit,last_visit:c.lastVisit}));reply.type('text/csv; charset=utf-8').header('Content-Disposition','attachment; filename="ryoiku-cities.csv"');return writeCsv(rows,columns);});
  app.get('/api/v1/export/countries.csv',async(request,reply)=>{const columns=['country_code','country_name','visited','city_count','visit_count','first_visit','last_visit'];const rows=countryQuery(sqlite,auth(request).id).map(c=>({country_code:c.code,country_name:c.name,visited:c.visited,city_count:c.cityCount,visit_count:c.visitCount,first_visit:c.firstVisit,last_visit:c.lastVisit}));reply.type('text/csv; charset=utf-8').header('Content-Disposition','attachment; filename="ryoiku-countries.csv"');return writeCsv(rows,columns);});
  app.get('/api/v1/backup.json',async(request,reply)=>{const user=auth(request);const backup={schemaVersion:1,createdAt:nowIso(),application:'ryoiku',cities:all(sqlite,'SELECT * FROM cities WHERE user_id=?',user.id),trips:all(sqlite,'SELECT * FROM trips WHERE user_id=?',user.id),visits:all(sqlite,'SELECT * FROM visits WHERE user_id=?',user.id),wishlist:all(sqlite,'SELECT * FROM wishlist_items WHERE user_id=?',user.id),settings:one(sqlite,'SELECT * FROM app_settings WHERE user_id=?',user.id)};reply.header('Content-Disposition','attachment; filename="ryoiku-backup.json"');return backup;});
  app.post('/api/v1/restore/preview',async(request,reply)=>{const body=z.object({backup:z.object({schemaVersion:z.literal(1),application:z.literal('ryoiku'),cities:z.array(z.record(z.string(),z.unknown())),trips:z.array(z.record(z.string(),z.unknown())),visits:z.array(z.record(z.string(),z.unknown())),wishlist:z.array(z.record(z.string(),z.unknown())),settings:z.record(z.string(),z.unknown()).nullable().optional()})}).parse(request.body),user=auth(request),id=randomUUID();sqlite.prepare('INSERT INTO import_previews(id,user_id,kind,payload,created_at,expires_at) VALUES(?,?,?,?,?,?)').run(id,user.id,'restore',JSON.stringify(body.backup),Date.now(),Date.now()+30*60_000);return {previewId:id,summary:{cities:body.backup.cities.length,trips:body.backup.trips.length,visits:body.backup.visits.length,wishlist:body.backup.wishlist.length}};});
  app.post('/api/v1/restore/commit',async(request,reply)=>{const {previewId,mode}=z.object({previewId:z.string().uuid(),mode:z.enum(['replace_travel_data','merge'])}).parse(request.body),user=auth(request),preview=one(sqlite,'SELECT payload FROM import_previews WHERE id=? AND user_id=? AND kind=? AND expires_at>?',previewId,user.id,'restore',Date.now());if(!preview)return reply.code(404).send(errorEnvelope(request,'PREVIEW_EXPIRED','Create a new restore preview.'));const data=JSON.parse(String(preview.payload)) as {cities:Row[];trips:Row[];visits:Row[];wishlist:Row[];settings?:Row};transaction(sqlite,()=>{if(mode==='replace_travel_data'){sqlite.prepare('DELETE FROM wishlist_items WHERE user_id=?').run(user.id);sqlite.prepare('DELETE FROM visits WHERE user_id=?').run(user.id);sqlite.prepare('DELETE FROM cities WHERE user_id=?').run(user.id);sqlite.prepare('DELETE FROM trips WHERE user_id=?').run(user.id);}for(const t of data.trips)sqlite.prepare(`INSERT OR IGNORE INTO trips(id,user_id,name,start_date,end_date,date_precision,notes,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)`).run(t.id,user.id,t.name,t.start_date??null,t.end_date??null,t.date_precision??'unknown',t.notes??null,t.created_at??nowIso(),t.updated_at??nowIso());for(const c of data.cities)sqlite.prepare(`INSERT OR IGNORE INTO cities(id,user_id,country_code,name,normalized_name,admin1,admin2,latitude,longitude,is_custom,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`).run(c.id,user.id,c.country_code,c.name,c.normalized_name??normalizeName(String(c.name)),c.admin1??null,c.admin2??null,c.latitude??null,c.longitude??null,c.is_custom??1,c.created_at??nowIso(),c.updated_at??nowIso());for(const v of data.visits)sqlite.prepare(`INSERT OR IGNORE INTO visits(id,user_id,country_code,city_id,trip_id,start_date,end_date,date_precision,notes,source,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`).run(v.id,user.id,v.country_code,v.city_id??null,v.trip_id??null,v.start_date??null,v.end_date??null,v.date_precision??'unknown',v.notes??null,'migration',v.created_at??nowIso(),v.updated_at??nowIso());for(const w of data.wishlist)sqlite.prepare(`INSERT OR IGNORE INTO wishlist_items(id,user_id,country_code,city_id,notes,created_at) VALUES(?,?,?,?,?,?)`).run(w.id,user.id,w.country_code,w.city_id??null,w.notes??null,w.created_at??nowIso());sqlite.prepare('DELETE FROM import_previews WHERE id=?').run(previewId);});audit(sqlite,'backup_restore','success',request.id,user.id,{mode});return {restored:true};});

  app.get('/api/v1/admin/info',async(request,reply)=>{const user=auth(request);if(user.role!=='admin')return reply.code(403).send(errorEnvelope(request,'AUTH_FORBIDDEN','Administrator access is required.'));return {database:'SQLite',journalMode:one(sqlite,'PRAGMA journal_mode')?.journal_mode,migrationVersion:one(sqlite,'SELECT MAX(version) version FROM schema_migrations')?.version,countryRows:one(sqlite,'SELECT COUNT(*) count FROM countries')?.count,mapDataset:'world-atlas 2.0.2'};});
  app.get('/api/v1/admin/diagnostics',async(request,reply)=>{const user=auth(request);if(user.role!=='admin')return reply.code(403).send(errorEnvelope(request,'AUTH_FORBIDDEN','Administrator access is required.'));const integrity=one(sqlite,'PRAGMA integrity_check')?.integrity_check;return {database:integrity==='ok'?'pass':'fail',countries:Number(one(sqlite,'SELECT COUNT(*) count FROM countries')?.count)>190?'pass':'fail',mapGeometry:'bundled',geocoder:'disabled'};});
  app.get('/api/v1/admin/logs',async(request,reply)=>{const user=auth(request);if(user.role!=='admin')return reply.code(403).send(errorEnvelope(request,'AUTH_FORBIDDEN','Administrator access is required.'));return all(sqlite,'SELECT event,result,request_id requestId,created_at createdAt FROM audit_events ORDER BY created_at DESC LIMIT 100');});

  if(options.staticRoot){await app.register(fastifyStatic,{root:options.staticRoot,prefix:'/'});app.setNotFoundHandler(async(request,reply)=>{if(request.url.startsWith('/api/'))return reply.code(404).send(errorEnvelope(request,'NOT_FOUND','Endpoint not found.'));return reply.type('text/html').send(await readFile(`${options.staticRoot}/index.html`,'utf8'));});}
  app.addHook('onClose',async()=>sqlite.close());
  return app;
}
