import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { buildApp } from '../src/server/app.js';

describe.sequential('Ryoiku API',()=>{
  let app:Awaited<ReturnType<typeof buildApp>>;let cookie='';let csrf='';let hamburgId='';
  const authHeaders=()=>({cookie:`ryoiku_session=${cookie}`,'x-csrf-token':csrf});
  beforeAll(async()=>{app=await buildApp({databasePath:join(mkdtempSync(join(tmpdir(),'ryoiku-')),'app.sqlite'),cookieSecure:false})});
  afterAll(async()=>app.close());
  it('reports process and dependency health',async()=>{expect((await app.inject('/health/live')).statusCode).toBe(200);expect((await app.inject('/health/ready')).json()).toEqual({status:'ready'})});
  it('starts with one-time setup and rejects a weak password',async()=>{expect((await app.inject('/api/v1/setup/status')).json()).toEqual({required:true,setupSecretRequired:false});const weak=await app.inject({method:'POST',url:'/api/v1/setup',payload:{username:'admin',password:'short'}});expect(weak.statusCode).toBe(400)});
  it('can protect first-run setup with a deployment secret',async()=>{const protectedApp=await buildApp({databasePath:join(mkdtempSync(join(tmpdir(),'ryoiku-protected-')),'app.sqlite'),cookieSecure:false,setupSecret:'synthetic-unit-test-setup-secret-0001'});expect((await protectedApp.inject('/api/v1/setup/status')).json()).toEqual({required:true,setupSecretRequired:true});const denied=await protectedApp.inject({method:'POST',url:'/api/v1/setup',payload:{username:'admin',password:'correct horse battery staple',setupSecret:'wrong'}});expect(denied.statusCode).toBe(401);await protectedApp.close()});
  it('creates the first administrator exactly once',async()=>{const created=await app.inject({method:'POST',url:'/api/v1/setup',payload:{username:'traveler',displayName:'Synthetic Traveler',password:'correct horse battery staple'}});expect(created.statusCode).toBe(201);expect((await app.inject({method:'POST',url:'/api/v1/setup',payload:{username:'other',password:'correct horse battery staple'}})).statusCode).toBe(409)});
  it('returns generic login failures and creates a server session',async()=>{const bad=await app.inject({method:'POST',url:'/api/v1/auth/login',payload:{username:'traveler',password:'wrong password'}});expect(bad.statusCode).toBe(401);expect(bad.json().message).toBe('Invalid credentials.');const login=await app.inject({method:'POST',url:'/api/v1/auth/login',payload:{username:'traveler',password:'correct horse battery staple'}});expect(login.statusCode).toBe(200);cookie=login.cookies[0]!.value;csrf=login.json().csrf;expect(cookie).not.toContain(csrf)});
  it('denies anonymous access and CSRF-less mutation',async()=>{expect((await app.inject('/api/v1/countries')).statusCode).toBe(401);expect((await app.inject({method:'POST',url:'/api/v1/places/search',payload:{query:'Prien'}})).statusCode).toBe(401);expect((await app.inject({method:'POST',url:'/api/v1/trips',headers:{cookie:`ryoiku_session=${cookie}`},payload:{name:'Blocked',datePrecision:'unknown'}})).statusCode).toBe(403);expect((await app.inject({method:'POST',url:'/api/v1/places/search',headers:{cookie:`ryoiku_session=${cookie}`},payload:{query:'Prien'}})).statusCode).toBe(403)});
  it('ships a versioned local country reference',async()=>{const response=await app.inject({url:'/api/v1/countries',headers:authHeaders()});expect(response.statusCode).toBe(200);expect(response.json().length).toBeGreaterThan(190);expect(response.json().find((c:{code:string})=>c.code==='DE').name).toBe('Germany')});
  it('derives city and country status from repeat visits',async()=>{const city=await app.inject({method:'POST',url:'/api/v1/cities',headers:authHeaders(),payload:{countryCode:'DE',name:'Hamburg',latitude:53.5511,longitude:9.9937}});expect(city.statusCode).toBe(201);hamburgId=city.json().id;const visit={countryCode:'DE',cityId:hamburgId,startDate:'2026-05-12',endDate:'2026-05-14',datePrecision:'day',notes:'Synthetic test visit'};const first=await app.inject({method:'POST',url:'/api/v1/visits',headers:authHeaders(),payload:visit});expect(first.statusCode).toBe(201);const duplicate=await app.inject({method:'POST',url:'/api/v1/visits',headers:authHeaders(),payload:visit});expect(duplicate.statusCode).toBe(409);const second=await app.inject({method:'POST',url:'/api/v1/visits',headers:authHeaders(),payload:{...visit,startDate:'2025-01-01',endDate:null,datePrecision:'year'}});expect(second.statusCode).toBe(201);const detail=(await app.inject({url:`/api/v1/cities/${hamburgId}`,headers:authHeaders()})).json();expect(detail.visited).toBe(true);expect(detail.visitCount).toBe(2);const country=(await app.inject({url:'/api/v1/countries/DE',headers:authHeaders()})).json();expect(country.visited).toBe(true);expect(country.cityCount).toBe(1)});
  it('detects and explicitly merges duplicate cities',async()=>{const duplicate=await app.inject({method:'POST',url:'/api/v1/cities',headers:authHeaders(),payload:{countryCode:'DE',name:'Hamburg',admin1:'Duplicate fixture'}});expect(duplicate.statusCode).toBe(201);expect(duplicate.json().duplicateOf).toBe(hamburgId);const duplicateId=duplicate.json().id;expect((await app.inject({method:'POST',url:'/api/v1/visits',headers:authHeaders(),payload:{countryCode:'DE',cityId:duplicateId,datePrecision:'unknown'}})).statusCode).toBe(201);const merged=await app.inject({method:'POST',url:`/api/v1/cities/${duplicateId}/merge`,headers:authHeaders(),payload:{targetCityId:hamburgId}});expect(merged.statusCode).toBe(200);expect((await app.inject({url:`/api/v1/cities/${hamburgId}`,headers:authHeaders()})).json().visitCount).toBe(3);expect((await app.inject({url:`/api/v1/cities/${duplicateId}`,headers:authHeaders()})).statusCode).toBe(404)});
  it('searches bundled places and atomically reuses a selected place for visits',async()=>{expect((await app.inject({method:'POST',url:'/api/v1/places/search',headers:authHeaders(),payload:{query:'P'}})).statusCode).toBe(400);const search=await app.inject({method:'POST',url:'/api/v1/places/search',headers:authHeaders(),payload:{query:'Prien'}});expect(search.statusCode).toBe(200);expect(search.json()).toMatchObject({attribution:'GeoNames · CC BY 4.0'});const german=search.json().results.find((place:{placeId?:string})=>place.placeId==='geonames:2852101');expect(german).toMatchObject({name:'Prien am Chiemsee',countryCode:'DE',countryName:'Germany',admin1:'Bavaria',latitude:47.85602,longitude:12.34623});const created=await app.inject({method:'POST',url:'/api/v1/visits',headers:authHeaders(),payload:{countryCode:'DE',placeId:german.placeId,startDate:'2024-06-01',datePrecision:'day'}});expect(created.statusCode).toBe(201);const cityId=created.json().cityId;expect((await app.inject({url:`/api/v1/cities/${cityId}`,headers:authHeaders()})).json()).toMatchObject({name:'Prien am Chiemsee',admin1:'Bavaria',latitude:47.85602,longitude:12.34623,visitCount:1});const repeated=await app.inject({method:'POST',url:'/api/v1/visits',headers:authHeaders(),payload:{countryCode:'DE',placeId:german.placeId,startDate:'2025-06-01',datePrecision:'day'}});expect(repeated.statusCode).toBe(201);expect(repeated.json().cityId).toBe(cityId);expect((await app.inject({url:`/api/v1/cities/${cityId}`,headers:authHeaders()})).json().visitCount).toBe(2);const savedSearch=await app.inject({method:'POST',url:'/api/v1/places/search',headers:authHeaders(),payload:{query:'Prien'}});expect(savedSearch.json().results[0]).toMatchObject({source:'saved',cityId,name:'Prien am Chiemsee'});const before=(await app.inject({url:'/api/v1/stats/summary',headers:authHeaders()})).json().visitCount;expect((await app.inject({method:'POST',url:'/api/v1/visits',headers:authHeaders(),payload:{countryCode:'US',placeId:german.placeId,datePrecision:'unknown'}})).statusCode).toBe(400);expect((await app.inject({method:'POST',url:'/api/v1/visits',headers:authHeaders(),payload:{countryCode:'DE',placeId:'geonames:999999999',datePrecision:'unknown'}})).statusCode).toBe(404);expect((await app.inject({url:'/api/v1/stats/summary',headers:authHeaders()})).json().visitCount).toBe(before)});
  it('supports UN, ISO and custom country counting totals',async()=>{const updated=await app.inject({method:'PATCH',url:'/api/v1/settings',headers:authHeaders(),payload:{countryCountingMode:'custom',customCountryTotal:222}});expect(updated.statusCode).toBe(200);expect((await app.inject({url:'/api/v1/stats/summary',headers:authHeaders()})).json()).toMatchObject({countryCountingMode:'custom',countryTotal:222})});
  it('retains visits when a trip is deleted',async()=>{const trip=await app.inject({method:'POST',url:'/api/v1/trips',headers:authHeaders(),payload:{name:'North Sea',datePrecision:'unknown'}});const tripId=trip.json().id;const visit=await app.inject({method:'POST',url:'/api/v1/visits',headers:authHeaders(),payload:{countryCode:'NL',tripId,datePrecision:'unknown'}});expect(visit.statusCode).toBe(201);expect((await app.inject({method:'DELETE',url:`/api/v1/trips/${tripId}`,headers:authHeaders()})).statusCode).toBe(204);const stored=(await app.inject({url:`/api/v1/visits/${visit.json().id}`,headers:authHeaders()})).json();expect(stored.tripId).toBeNull()});
  it('previews invalid CSV without partial writes',async()=>{const before=(await app.inject({url:'/api/v1/stats/summary',headers:authHeaders()})).json().visitCount;const csv='record_type,country_code,city_name,date_precision\nvisit,ZZ,Nowhere,day';const preview=await app.inject({method:'POST',url:'/api/v1/import/csv/preview',headers:authHeaders(),payload:{csv}});expect(preview.statusCode).toBe(200);expect(preview.json().summary.errors).toBe(1);const commit=await app.inject({method:'POST',url:'/api/v1/import/csv/commit',headers:authHeaders(),payload:{previewId:preview.json().previewId}});expect(commit.statusCode).toBe(409);expect((await app.inject({url:'/api/v1/stats/summary',headers:authHeaders()})).json().visitCount).toBe(before)});
  it('commits valid CSV atomically and exports spreadsheet-safe text',async()=>{const csv='record_type,country_code,country_name,city_name,visited_from,date_precision,notes\nvisit,FR,France,Lyon,2024-03-01,month,=synthetic';const preview=await app.inject({method:'POST',url:'/api/v1/import/csv/preview',headers:authHeaders(),payload:{csv}});const commit=await app.inject({method:'POST',url:'/api/v1/import/csv/commit',headers:authHeaders(),payload:{previewId:preview.json().previewId}});expect(commit.statusCode).toBe(200);expect(commit.json()).toMatchObject({createdVisits:1,createdCities:1});const exported=await app.inject({url:'/api/v1/export/visits.csv',headers:authHeaders()});expect(exported.statusCode).toBe(200);expect(exported.body).toContain("'=synthetic")});
  it('backs up, previews and transactionally restores travel data',async()=>{const backup=(await app.inject({url:'/api/v1/backup.json',headers:authHeaders()})).json();expect(backup.visits.length).toBeGreaterThan(0);expect(JSON.stringify(backup)).not.toContain('password_hash');const preview=await app.inject({method:'POST',url:'/api/v1/restore/preview',headers:authHeaders(),payload:{backup}});expect(preview.statusCode).toBe(200);const restore=await app.inject({method:'POST',url:'/api/v1/restore/commit',headers:authHeaders(),payload:{previewId:preview.json().previewId,mode:'replace_travel_data'}});expect(restore.statusCode).toBe(200);expect((await app.inject({url:'/api/v1/stats/summary',headers:authHeaders()})).json().visitCount).toBe(backup.visits.length)});
  it('revokes the session on logout',async()=>{expect((await app.inject({method:'POST',url:'/api/v1/auth/logout',headers:authHeaders()})).statusCode).toBe(204);expect((await app.inject({url:'/api/v1/auth/me',headers:authHeaders()})).statusCode).toBe(401)});
});
